### ISSUE TITLE
gay

### ISSUE THREAD

**Issue by mciem** [sfx2me/discord-server-cloner#1]
wowzers what a gay code!

**Comment by xKiian** [comment]
![Screenshot_20230307-210714.png](https://user-images.githubusercontent.com/88455386/223540408-6ffd8c54-4e1f-42d6-9f0c-a67081521513.png)

Please start using f strings or how to code clean before hating💀

**Comment by mciem** [comment]
Please start using f strings or how to code clean before hating💀
